// Example array from courses.csv
const courses = [
  { course_code: "MATH1001", name: "Algebra & Trigonometry" },
  { course_code: "MATH1002", name: "Calculus I" },
  { course_code: "MATH1003", name: "Statistics & Probability" },
  { course_code: "MATH1004", name: "Geometry & Logic" },
  { course_code: "ENGL2001", name: "World Literature" },
  { course_code: "ENGL2002", name: "Creative Writing" },
  { course_code: "ENGL2003", name: "Shakespearean Drama" },
  { course_code: "ENGL2004", name: "Advanced Composition" },
  { course_code: "SCI3001", name: "Biology: Human Systems" },
  { course_code: "SCI3002", name: "Chemistry Fundamentals" },
  { course_code: "SCI3003", name: "Environmental Science" },
  { course_code: "SCI3004", name: "Physics: Mechanics" },
  { course_code: "HIST4001", name: "Modern World History" },
  { course_code: "HIST4002", name: "Canadian History" },
  { course_code: "HIST4003", name: "Ancient Civilizations" },
  { course_code: "HIST4004", name: "Political Revolutions" },
  { course_code: "ART5001", name: "Drawing & Painting" },
  { course_code: "ART5002", name: "Sculpture & Ceramics" },
  { course_code: "ART5003", name: "Digital Photography" },
  { course_code: "ART5004", name: "Mixed Media & Design" },
  { course_code: "COMP6001", name: "Computer Science Principles" },
  { course_code: "COMP6002", name: "Web Development Basics" },
  { course_code: "COMP6003", name: "Cybersecurity Awareness" },
  { course_code: "COMP6004", name: "Game Design & Programming" },
  { course_code: "ECON7001", name: "Microeconomics" },
  { course_code: "ECON7002", name: "Macroeconomics" },
  { course_code: "ECON7003", name: "Financial Literacy" },
  { course_code: "ECON7004", name: "Business Analytics" },
  { course_code: "LANG8001", name: "French Language & Culture" },
  { course_code: "LANG8002", name: "Spanish for Beginners" },
  { course_code: "LANG8003", name: "Japanese: Basic Communication" },
  { course_code: "LANG8004", name: "Latin & Classical Literature" },
  { course_code: "LANG8005", name: "Italian Language & Culture" },
  { course_code: "LANG8006", name: "Mandarin for Beginners" },
  { course_code: "LANG8007", name: "German Language & History" },
  { course_code: "LANG8008", name: "American Sign Language" },
  { course_code: "MUS9001", name: "Music Theory & Composition" },
  { course_code: "MUS9002", name: "Jazz & Contemporary Music" },
  { course_code: "MUS9003", name: "Orchestration & Arranging" },
  { course_code: "MUS9004", name: "Vocal Performance Techniques" },
  { course_code: "PHED1001", name: "Sports & Athletic Training" },
  { course_code: "PHED1002", name: "Health & Wellness Studies" },
  { course_code: "PHED1003", name: "Mindfulness & Stress Management" },
  { course_code: "PHED1004", name: "Yoga & Physical Fitness" },
  { course_code: "TECH2001", name: "Robotics & Automation" },
  { course_code: "TECH2002", name: "Electrical Engineering Basics" },
  { course_code: "TECH2003", name: "Mechanical Systems & Design" },
  { course_code: "TECH2004", name: "Drone Technology & Applications" },
  { course_code: "PSYC3001", name: "Introduction to Psychology" },
  { course_code: "PSYC3002", name: "Cognitive Science & Memory" },
  { course_code: "PSYC3003", name: "Social Psychology & Behavior" },
  { course_code: "PSYC3004", name: "Developmental Psychology" },
  { course_code: "LAW4001", name: "Criminal Justice & Ethics" },
  { course_code: "LAW4002", name: "Civil Rights & Legal Studies" },
  { course_code: "LAW4003", name: "International Law & Diplomacy" },
  { course_code: "LAW4004", name: "Business & Corporate Law" },
  { course_code: "PHIL5001", name: "Ethics & Moral Philosophy" },
  { course_code: "PHIL5002", name: "Logic & Critical Thinking" },
  { course_code: "PHIL5003", name: "Metaphysics & Existentialism" },
  { course_code: "PHIL5004", name: "Philosophy of Science" },
  { course_code: "ENV6001", name: "Climate Change & Sustainability" },
  { course_code: "ENV6002", name: "Renewable Energy & Conservation" },
  { course_code: "ENV6003", name: "Urban Planning & Environmental Design" },
  { course_code: "ENV6004", name: "Marine Biology & Oceanography" },
];

export default courses;
